name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag llkevin13579/ifconfig-me:latest . && docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }} && docker push llkevin13579/ifconfig-me:latest
